### ISSUE TITLE
grab exports all at once to avoid rate limiting

### ISSUE THREAD

**Issue by souporserious** [tiltshift/figmint#14]
Figma's API only allows 25 requests/minute so if you have more icons than that you can get rate limited pretty quickly 😅. I think we just need to refactor the `addImageUrlToExport` function to pass all of the ids, I did something similar in [Unicon](https://github.com/souporserious/unicon/blob/master/packages/unicon/src/get-svgs-from-figma.js#L81). I'll try to get to a PR today.

**Comment by chrisdrackett** [comment]
Yeah, I ran into this as well, but thought about moving to Diez around the same time and never got to fixing it. That being said, I think I've decided to move back to using figmint so I'm going to be a lot more active here. @souporserious were you able to look at this yet?

**Comment by souporserious** [comment]
Yup! I ended up making another library that just handles the exports since that's all I needed, but I'll try and take a look at adding it here when I get a chance. This is the shape I have it return right now:

![image](https://user-images.githubusercontent.com/2762082/71210496-d93c4800-2261-11ea-8d8a-ff8a43ff3fc3.png)

**Comment by chrisdrackett** [comment]
ok, I'll give it a go!

**Comment by chrisdrackett** [comment]
@souporserious FYI this should be fixed. Would love if you took a look but understand if you have your own solution now!

**Comment by souporserious** [comment]
Awesome! Looks great from what I can tell 🎉I'll check it out when I get a chance. Thanks for getting that fixed so quickly 🙏
